### ISSUE TITLE
machine learning engine execution error

### ISSUE THREAD

**Issue by djglowny** [RPI-WCL/pilots#2] opened 2017-02-13 22:04 UTC
This error occurs on **Ubuntu 14.04.5** with **Python version 2.7.10**. When attempting to execute:
```bash
python engineIO.py definitions/bayes_config.json
```
from **pilots/util/learningmodel/engine** on the **learn_dev** branch as an example of using the machine learning engine, the following error output message occurs:

```bash
Traceback (most recent call last):
  File "engineIO.py", line 100, in <module>
    env = train_model(json_file)
  File "engineIO.py", line 14, in train_model
    return _load(json_file_name)
  File "engineIO.py", line 87, in _load
    read_model(env, json_dict[K.M])
  File "engineIO.py", line 57, in read_model
    env.feature = env.transform(baseenv.BaseEnv.data_transformer, schema=env.get_schema_info(), constant=env.get_constant(), definition=json_dict[K.A_FEATURES])
  File "/home/glownd/Documents/PILOTS_research/git_repos/pilots/pilots/util/learningmodel/engine/scbase/baseenv.py", line 125, in transform
    return transformer(self.data, **parameters)
  File "/home/glownd/Documents/PILOTS_research/git_repos/pilots/pilots/util/learningmodel/engine/scbase/baseenv.py", line 196, in data_transformer
    X = np.apply_along_axis(def_transformer, 1, npmatrix)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/shape_base.py", line 91, in apply_along_axis
    res = func1d(arr[tuple(i.tolist())], *args, **kwargs)
  File "<string>", line 1, in <lambda>
  File "/usr/local/lib/python2.7/dist-packages/numpy/matrixlib/defmatrix.py", line 318, in __getitem__
    out = N.ndarray.__getitem__(self, index)
IndexError: index 3 is out of bounds for axis 0 with size 1
```

**Comment by KeyboardNerd** [comment] 2017-02-14 05:54
Hi, I've committed the change, basically the issue is caused by change of dimensions in numpy array and numpy matrix. Please update your local repo.

**Closed as completed** 2017-02-22 03:28 UTC
